# Generated by Django 2.2.1 on 2019-06-17 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('dprice', models.PositiveIntegerField()),
                ('wprice', models.PositiveIntegerField()),
                ('mprice', models.PositiveIntegerField()),
                ('img1', models.ImageField(null=True, upload_to='images/')),
                ('img2', models.ImageField(null=True, upload_to='images/')),
                ('available_for_selling', models.CharField(choices=[('y', 'YES'), ('n', 'NO')], default='n', max_length=1)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
